### ISSUE TITLE
Error in gulp-less/index.js

### ISSUE THREAD

**Issue by bhj** [dozoisch/koa-react-full-example#16]
Hi, thanks for this example. I haven't tried previous versions but with v0.3.2 when it comes to `gulp install` I get

```
[18:49:13] Using gulpfile ~/Sites/koa-react-full-example/gulpfile.js
[18:49:13] Starting 'jsx-compile'...
[18:49:13] Starting 'copy-js'...
[18:49:13] Starting 'less-compile'...
[18:49:13] Starting 'write-build-info'...
[18:49:13] Finished 'copy-js' after 26 ms
/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-if/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-if/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/Brandon/Sites/koa-react-full-example/node_modules/gulp-if/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
```

`npm install` and `npm install -g gulp` both worked, and I did `npm update -g` for good measure but no change. OS X 10.10.2 with Node 0.12.

**Comment by dozoisch** [comment]
That seems like an error in gulp-less, what is the gulp-less version you have? Just so I can try to repro.

**Comment by bhj** [comment]
Yes, I have 2.0.3 so that may be it. Still getting my head around the build flow; thanks for looking into it!

**Comment by dozoisch** [comment]
I've updated the deps to 3.0.0 and from their log it seem like they had a bug that slipped at the end of 2.0.x! So it should be working now! If it works now you can go ahead and close the issue.

**Comment by bhj** [comment]
Looking good, thanks!
