### ISSUE TITLE
Error: Cannot find module 'jstransform/visitors/es6-arrow-function-visitors'

### ISSUE THREAD

**Issue by sergenikitin** [dozoisch/koa-react-full-example#17]
```
[serge:mbp koa-react-full-example-master]$ npm install
[serge:mbp koa-react-full-example-master]$ gulp install
module.js:322
    throw err;
          ^
Error: Cannot find module 'jstransform/visitors/es6-arrow-function-visitors'
    at Function.Module._resolveFilename (module.js:320:15)
    at Function.Module._load (module.js:262:25)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/serge/projects/test/koa-react-full-example-master/node_modules/gulp-react/node_modules/react-tools/vendor/fbtransform/visitors.js:2:25)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
[serge:mbp koa-react-full-example-master]$ node --version
v1.3.0
```

**Comment by dozoisch** [comment]
Ill check that out sorry for the delay

**Comment by dozoisch** [comment]
@sergenikitin What is that node version 1.3.0? Just curious? Is that IOJS? I havn't tested on iojs yet.

**Comment by dozoisch** [comment]
Since I can not repro and don't have any more info, I'll close this. Feel free to reopen if needed.
