### ISSUE TITLE
upgrade to mongoose 4.0

### ISSUE THREAD

**Issue by dozoisch** [dozoisch/koa-react-full-example#20]

**Comment by filmackay** [comment]
How difficult/big a deal is this?

I've just tried a smoke test on this, but getting stuck on ```npm test``` failing:
```
module.js:338
    throw err;
    ^
Error: Cannot find module '../../build/stats.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/src/koa-react-full-example/src/controllers/index.js:1:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/src/koa-react-full-example/config/routes.js:4:23)
```

**Comment by dozoisch** [comment]
Run `npm run build` once nefore the tests to generate the stat file.

**Comment by filmackay** [comment]
Cheers @dozoisch - just figured that one out :)

Might be worth looking at the chronology of the 'getting started' - this is missing prior to the first mention of npm test in Instructions.

What issues do you expect with Mongoose 4.0; is this just conservatism or do you have some 'known unknowns' in mind.

**Comment by dozoisch** [comment]
The first issue is with the save that is now promise based. So that has to be migrated. For the rest I am not sure

**Comment by filmackay** [comment]
Well, the tests pass with latest Mongoose :)

**Comment by filmackay** [comment]
So no changes in mongoose API requiring changes - promise-ish? Looks like a very clean upgrade!

**Comment by dozoisch** [comment]
Yeah I thought there would be issues, but seemed to work right away!
