### ISSUE TITLE
npm run hot-dev-server 

### ISSUE THREAD

**Issue by debonair** [dozoisch/koa-react-full-example#30]
when I run

npm run hot-dev-server

i get

> koa-react-full-example@0.5.1 hot-dev-server /home/duma/Projects/Personal/koa-react-full-example
> webpack-dev-server --content-base public -ds --config webpack.config.js --hot --progress --colors --port 2992 --inline

 70% 1/1 build moduleshttp://localhost:2992/
webpack result is served from //localhost:2992/_assets/
content is served from /home/duma/Projects/Personal/koa-react-full-example/public
/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/node/NodeWatchFileSystem.js:29
                throw new Error("Invalid arguments: 'delay'");
                      ^
Error: Invalid arguments: 'delay'
    at NodeWatchFileSystem.watch (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/node/NodeWatchFileSystem.js:29:9)
    at Watching.watch (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:78:47)
    at Watching._done (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:74:8)
    at Watching.<anonymous> (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:52:18)
    at Tapable.emitRecords (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:271:37)
    at Watching.<anonymous> (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:49:19)
    at /home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:264:11
    at Tapable.applyPluginsAsync (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:261:8)
    at Tapable.<anonymous> (/home/duma/Projects/Personal/koa-react-full-example/node_modules/webpack/lib/Compiler.js:256:14)

**Comment by dozoisch** [comment]
I'll try to test that out asap! Must be related to some dependency that did a patch and introduced a bug.

**Comment by rickyduck** [comment]
I'm having the same issue, any solution yet?

**Comment by mathieumg** [comment]
+1 :+1:

**Comment by dozoisch** [comment]
@rickyduck I really haven't had time to check it out yet... sorry I'll try to look at it asap.

**Comment by dozoisch** [comment]
@rickyduck @debonair should be fixed as of 0.5.2. 

It seemed to be an issue with webpack 1.8.11

**Comment by rickyduck** [comment]
@dozoisch Thanks for the swift response. I can confirm this is all working now for me

**Comment by debonair** [comment]
@dozoisch thanks works great!

**Comment by mathieumg** [comment]
@dozoisch Thanks for fixing! :dancers:
