### ISSUE TITLE
Erro with npm run prod on Mac 10.10.5 (Yosemite): Cannot find module 'bcrypt'

### ISSUE THREAD

**Issue by rcholic** [dozoisch/koa-react-full-example#37]
My node version is the latest v5.7.0 and did `npm install` in the downloaded project, however, I got the following errors when running `npm run prod`:

```
Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/xxx/Desktop/Code/nodeJS/koa/koa-react-full-example/lib/bcrypt-thunk.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/xxx/Desktop/Code/nodeJS/koa/koa-react-full-example/src/models/user.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

I did `npm install bcrypt --save` as well, but the problem persists. any ideas where might be wrong?

**Comment by dozoisch** [comment]
bcrypt needs to be built natively. Do you have a c++ compiler installed? (Try typing `g++ -v` in your terminal)
